package com.imps.cms.model;

public enum DeadlineType {
    SUBMIT_PROPOSAL,
    BID,
    ASSIGN_PAPERS_TO_REVIEWERS,
    REVIEW,
    ACCEPT_PAPERS,
    IMPROVE_PAPERS,
    CREATE_SECTIONS,
    UPLOAD_PRESENTATION,
    REGISTER_LISTENER
}
